### ISSUE TITLE
Missing URL field in API data

### ISSUE THREAD

**Issue by MarkGalloway** [Tamarabyte/cmput410-project#11]
Some of the example API spec has URL in the author section but not in other author sections. We need to figure out where to store this redundant url

@Dylanlan  is going to get this clarified with Hindle, then a fix needs to happen

**Comment by derekdowling** [comment]
Protip, best way is to store it as a Django model property that is never persisted and then just build it from host and id.

**Comment by MarkGalloway** [comment]
wontfix
