### ISSUE TITLE
Add Team 8 to Factory 

### ISSUE THREAD

**Issue by MarkGalloway** [Tamarabyte/cmput410-project#55]
http://cs410.cs.ualberta.ca:41084/

They are pulling from us already we just need to be able to do the reverse and then we will have our minimum 2 groups for the submissions.

Check their API docs for the auth and what not. Calls should be very similar to ours.

**Comment by mkarpoff** [comment]
I've made all the request factories According to their pages they are the exact same as ours so that was nice
